<$PLAN9/src/mkhdr

TARG=nedmail

LIB=../common/libcommon.a\
	/usr/local/plan9/lib/libthread.a

HFILES=../common/common.h

OFILES=nedmail.$O

BIN=$PLAN9/bin/upas

<$PLAN9/src/mkone
CFLAGS=$CFLAGS -I../common
