#!/bin/bash

fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/usr/local/plan9}

export INSIDE_P9P=true
export INSIDE_9TERM=true
export DEVDRAW="$(dirname "$0")/devdraw"

cd $HOME

arch=x86_64
if arch -arch arm64 date >/dev/null 2>&1; then
	arch=arm64
fi
case "$SHELL" in
*/rc)
	echo '
		if(! ~ $PLAN9/bin $path)
			path=($path $PLAN9/bin)
		arch -arch '$arch' $PLAN9/bin/9term -l -W600x800 &
	' | $SHELL -l
	exit 0
	;;
*/bash)
	. ~/.bash_profile
	;;
*)
	. ~/.profile
	;;
esac

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi

ARGS=(-s)
ARGS+=(-l -W600x800)
if [ ! -z "$fixfont" ]; then
	ARGS+=(-f "$fixfont")
fi

plumber &
fontsrv &

arch -arch $arch /bin/bash -c 'exec -a 9term "$@"' -- "$PLAN9/bin/9term" "${ARGS[@]}" "$@"
exit 0

