#!/bin/bash

fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/usr/local/plan9}

export INSIDE_P9P=true
export INSIDE_ACME=true
export tabstop=8

cd $HOME

arch=x86_64
if arch -arch arm64 date >/dev/null 2>&1; then
	arch=arm64
fi

case "$SHELL" in
*/rc)
	echo '
		if(! ~ $PLAN9/bin $path)
			path=($path $PLAN9/bin)
		arch -arch '$arch' $PLAN9/bin/sam &
	' | $SHELL -l
	exit 0
	;;
*/bash)
	. ~/.bash_profile
	;;
*)
	. ~/.profile
	;;
esac

ARGS=(-a)
if [ ! -z "$fixfont" ]; then
	export font=$fixfont
fi

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi

exec arch -arch "$arch" \
	/bin/bash -c 'exec -a sam "$@"' -- "$PLAN9/bin/sam" "${ARGS[@]}" "$@"
exit 0
