#!/bin/sh

sudo rm -rf /usr/local/plan9/*
sudo mkdir -p /usr/local/plan9
sudo cp -r ./* /usr/local/plan9/
cd /usr/local/plan9
sudo ./INSTALL

su -s /bin/sh -c 'export PLAN9=/usr/local/plan9 && export PATH=$PATH:$PLAN9/bin && cd $PLAN9/src/cmd/upas/nfs && mk install && cd $PLAN9/src/cmd/upas && mk install'

