#!/bin/sh

sudo rm -rf /usr/local/plan9/*
sudo mkdir -p /usr/local/plan9
sudo cp -r ./* /usr/local/plan9/
cd /usr/local/plan9
sudo ./INSTALL

PLAN9=/usr/local/plan9
cd $PLAN9/src/cmd/upas/nfs
sudo mk install

cd $PLAN9/src/cmd/upas
sudo mk install

