<$PLAN9/src/mkhdr

TARG=pop3
OFILES=pop3.$O

BIN=$PLAN9/bin/upas
LIB=\
	../common/libcommon.a\
	/usr/local/plan9/lib/libauth.a\
	/usr/local/plan9/lib/libthread.a\

<$PLAN9/src/mkone
CFLAGS=$CFLAGS -I../common
