
install:V:
	cp $PLAN9/bin/devdraw ./9term.app/Contents/MacOS/
	cp -r 9term.app /Applications/
	cp $PLAN9/bin/devdraw ./Acme.app/Contents/MacOS/
	cp -r Acme.app /Applications/
	cp $PLAN9/bin/devdraw ./Sam.app/Contents/MacOS/
	cp -r Sam.app /Applications/
	cp -r Plumb.app /Applications/
