<$PLAN9/src/mkhdr

TARG=scanmail\
	testscan

OFILES=	common.$O

HFILES=	spam.h\
	../common/sys.h\

LIB=	../common/libcommon.a

BIN=$PLAN9/bin/upas
<$PLAN9/src/mkmany
CFLAGS=$CFLAGS -I../common

scanmail.$O:	scanmail.c
	$CC $CFLAGS scanmail.c
