#!/bin/bash

fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/usr/local/plan9}

export INSIDE_P9P=true
export INSIDE_ACME=true
export tabstop=8
export DEVDRAW="$(dirname "$0")/devdraw"

cd $HOME

arch=x86_64
if arch -arch arm64 date >/dev/null 2>&1; then
	arch=arm64
fi

case "$SHELL" in
*/rc)
	echo '
		if(! ~ $PLAN9/bin $path)
			path=($path $PLAN9/bin)
		args=(-a)
		if(! ~ $#fixfont 0)
			args=($args -F $fixfont)
		if(! ~ $#varfont 0)
			args=($args -f $varfont)
		arch -arch '$arch' $PLAN9/bin/acme $args &
	' | $SHELL -l
	exit 0
	;;
*/bash)
	. ~/.bash_profile
	;;
*)
	. ~/.profile
	;;
esac

ARGS=(-a)
if [ ! -z "$fixfont" ]; then
	ARGS+=(-F "$fixfont")
fi
if [ ! -z "$varfont" ]; then
	ARGS+=(-f "$varfont")
fi

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi

exec arch -arch "$arch" \
	/bin/bash -c 'exec -a acme "$@"' -- "$PLAN9/bin/acme" "${ARGS[@]}" "$@"
exit 0

