<$PLAN9/src/mkhdr

TARG=\
	deliver\
	list\
	mbappend\
	mbcreate\
	mbremove\
	token\

LIB=../common/libcommon.a

OFILES=readaddrs.$O

BIN=$PLAN9/bin/upas
<$PLAN9/src/mkmany

CFLAGS=$CFLAGS -I../common
