#!/bin/bash
INSIDE_ACME=true
export tabstop=8
fshell=$(finger $(whoami) | sed -n 's/.*Shell: //p' | sed 1q)
SHELL=${fshell:-$SHELL}
PLAN9=${PLAN9:-/usr/local/plan9}
cd $HOME
arch=x86_64
if arch -arch arm64 date >/dev/null 2>&1; then
	arch=arm64
fi
case "$SHELL" in
*/rc)
	echo '
		if(! ~ $PLAN9/bin $path)
			path=($path $PLAN9/bin)
		arch -arch '$arch' $PLAN9/bin/9term -l -W600x800 &
	' | $SHELL -l
	exit 0
	;;
*/bash)
	. ~/.bash_profile
	;;
*/zsh)
	. ~/.zprofile
	;;
*)
	. ~/.profile
	;;
esac

if ! [[ :$PATH: =~ :$PLAN9/bin: ]]
then
	PATH=$PATH:$PLAN9/bin
fi

# create 9 namespace
if $PLAN9/bin/9p stat acme >/dev/null 2>&1; then
  NAMESPACE=/tmp/ns.$USER.$RANDOM
  export NAMESPACE
  mkdir -p $NAMESPACE
else
  rm -f $(namespace)/acme
fi

# collect dependencies
deps=("plumber" "fontsrv")
acmedeps=()
if [[ ! -z "$ACME_DEPS" ]]; then
	IFS=',' read -r -a acmedeps <<< "$ACME_DEPS"
fi

# launch soft dependencies for acme
for dep in "${deps[@]}"; do
	if ! pgrep -x "$dep" > /dev/null; then
		echo "launching $dep"
		"$dep" &
	fi
done

# append font arguments
ARGS=()
if [[ ! -z "$FIXFONT" ]]; then
	ARGS+=("-F $FIXFONT")
fi
if [[ ! -z "$VARFONT" ]]; then
	ARGS+=("-f $VARFONT")
fi
fontargs="${ARGS[*]}" 

# start acme and capture pid
arch -arch $arch $PLAN9/bin/acme -a $fontargs &
acmepid=$!

# wait for acme to launch
sleep 1

# launch dependencies that depend on acme
for dep in "${acmedeps[@]}"; do
	if ! pgrep -x "$dep" > /dev/null; then
		echo "launching $dep"
		"$dep" &
	fi
done

# wait for acme to finish before exiting
wait $acmepid

exit 0

